project:
  type: website
  output-dir: docs

website:
  title: "Annual HS Outreach - GMU Statistics"
  
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: dv.qmd
        text: Data Visualizations
        
author:
      - name: Dr. Isuru Dassanayake
        affiliations:
          - name: Department of Statistics - George Mason University
          

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

